#   Numpy
### Industrial Hook
#### list is inflexible, large, slow so we use numpy for faster computations, less memory, powerful mathematical operations, multi-dimensional arrays:  pandas, scikit-learn,tensorflow,pytorch and opencv

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3, "string"])
print(array)
print(type(array))

['1' '2' '3' 'string']
<class 'numpy.ndarray'>


In [3]:
# Numpy array of data
array1 = np.array([1,2,3,4,5])
print(array1)
type(array1)

[1 2 3 4 5]


numpy.ndarray

In [7]:
number_list = [1,2,3,4,5]
nparray = np.array(number_list)
print(nparray)
print(type(nparray))
print(type(number_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>


In [16]:
array0 = np.zeros(10)
array0 = np.zeros(10, dtype=int)
array1 = np.ones(10)
array2 = np.arange(0, 10, 1)
array3 = np.linspace(0, 10, 10)
array4 = np.random.rand(10)
array5 = np.random.randint(0, 10, 10)

print(array0)
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(type(array0[0]))
print(type(array4))



[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[0.54740946 0.74169225 0.98092177 0.21205099 0.29994727 0.22723652
 0.74116734 0.72970796 0.71307392 0.51816972]
[4 6 5 6 3 9 9 4 5 4]
<class 'numpy.int64'>
<class 'numpy.ndarray'>


In [34]:
a = np.arange(5)
print(a)

a = range(5)
print(a)
print(list(a))
print("\n")

b = np.arange(5, 10)
print(b)

c = np.arange(5,10,2)
print(c)
print(type(c[0]))

d = np.arange(5, 0, -1)
print(d)

#range and arange are similar but arange returns an array and range returns a list
#range does not support float values but arange does
#arange returns an array while range returns a list



[0 1 2 3 4]
range(0, 5)
[0, 1, 2, 3, 4]


[5 6 7 8 9]
[5 7 9]
<class 'numpy.int64'>
[5 4 3 2 1]


In [37]:
line = np.linspace(0,1,5)
print(line)

lin1 = np.linspace(0,1,5, endpoint=False)
print(lin1)

lin2 = np.linspace(0,1,5, endpoint=True)
print(lin2)

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]
[0.   0.25 0.5  0.75 1.  ]


In [46]:
# random number
random_num = np.random.randint(5,5467)
print(random_num)

random_num1 = np.random.randint(5,5467, 10)
print(random_num1)

random_num2 = np.random.randint(5,5467, (3,4))
print(random_num2)
print(type(random_num2))

print(np.random.rand(5))
print("\n\n")
#using random.uniform to generate random numbers between 0 and 1
random_num3 = np.random.uniform(5,5467)
print(random_num3)

random_num4 = np.random.uniform(5,5467, 10)
print(random_num4)

random_num5 = np.random.uniform(5,5467, (3,4))
print(random_num5)

2103
[3703 5129 2227 5002 5249 3331   37 2144 4676 3934]
[[ 261 1376 3633 4513]
 [1458 2255  691 1389]
 [4092  428 3567 3479]]
<class 'numpy.ndarray'>
[0.02161553 0.66861374 0.05225975 0.15840481 0.48911812]



3481.107220429749
[2565.75692738 4574.64477403 2899.2356587  3521.05936842 5445.66824885
 1967.3763003  3417.82824953 1324.16946905 3485.27616758 2596.92351717]
[[ 341.48617124  880.31872928  268.4732092  1549.64164735]
 [3387.84437385 1185.37243484 4317.44842236   38.4599136 ]
 [4164.85341332 1660.56533561 2082.25700496 1093.50962858]]


In [48]:
#modern way of using random uniform
#traditional can cause interference to thread by making global 

rng = np.random.default_rng()

print(rng.uniform(size=5))

print(rng.uniform(low=10.0, high=20.0, size=5))

[0.09237576 0.97729455 0.74241825 0.72000108 0.32445071]
[18.82698988 18.35781292 10.02754536 15.20760009 14.97279251]


# Array Indexing

In [3]:
import numpy as np
array1 = np.array([1,2,3,4])

print(array1[2] + array1[3])

print(array1[-(len(array1))])

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Attributes of array in np\n")
print(array1.ndim)  #dimension
print(array1.shape) #size of array
print(array1.size)  #number of size
print(array1.dtype) #type of data stored in array
print(array1.itemsize)  #size of each element in bytes
print(array1.nbytes)    #total memory used 

7
1
Attributes of array in np

2
(3, 3)
9
int64
8
72


# Upcasting

In [8]:
#vectorization in numpy

prices = np.array([23,43,500])
prices = prices * 1.50
print(prices)


#traditional way in py is using for loop
for i in range(len(prices)):
    prices[i] = prices[i] * 5
print(prices)

[ 34.5  64.5 750. ]
[ 172.5  322.5 3750. ]


In [10]:
#Vectorized Arithmetic
#addition,multiplication and so on
print(prices+2)
print(prices*2)

[ 174.5  324.5 3752. ]
[ 345.  645. 7500.]


In [17]:
a = np.array([1,2,3,4])
b = np.array([[3,4,6,5],[3,1,2,4],[2,4,6,7]])

print(a+b)
print(a*b)


#Array compatibility
#   ##same size of column
#   ##one of the row dimension should be 1

# ''' Example:  here nparray
#                 a = (1 x 4)
#                 b = (3 x 4)
#                 '''

[[ 4  6  9  9]
 [ 4  3  5  8]
 [ 3  6  9 11]]
[[ 3  8 18 20]
 [ 3  2  6 16]
 [ 2  8 18 28]]


In [21]:
# Aggregate Functions
sales = np.array([
    [100,120,90],
    [200,180,220],
    [150,170,160]
])

print(sales.sum())
print(sales.mean())
print(sales.std())

1390
154.44444444444446
41.66296279833928


In [24]:
median = np.median(sales)
print(median)

# median cannot be accessed by instance

print(sales.sum(axis=1))
# summ across the columns (row-wise result)

print(sales.sum(axis=0))
# sum down the rows (column-wise  result)

160.0
[310 600 480]
[450 470 470]


In [3]:
import numpy as np

num1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(num1[::-1])
print(num1[::-2])
print(num1[1:9:-1])
print(num1[1:9:-2])
print(num1[9:1:-2])

[10  9  8  7  6  5  4  3  2  1]
[10  8  6  4  2]
[]
[]
[10  8  6  4]


In [5]:
array1 = np.array([1,2,3,4,5])
boolean = array1 > 3
print(boolean)


[False False False  True  True]


In [6]:
# create an array of numbers
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

# make a copy of the array
numbers_copy = numbers.copy()

# change all even nubmers to 0 in the copy
numbers_copy[numbers % 2 == 0] = 0

# print the modified copy
print(numbers_copy)
print(numbers)

[1 0 3 0 5 0 7 0 9 0]
[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
num = np.array(numbers)
print(num)
print("\n")
odd_numbers = num[num%2 == 1].copy()
print(odd_numbers)

indexed = num[num > num[2]].copy()
print(indexed)

fancy_index = num[[1,2,5,7]]
print(fancy_index)


[ 1  2  3  4  5  6  7  8  9 10]


[1 3 5 7 9]
[ 4  5  6  7  8  9 10]
[2 3 6 8]


In [39]:
#1D array operations

first = np.array([1,5,5,7])
second = np.array([2,3,6,8])

suum = sum(first, second)
add = np.add(first,second)
print(suum)
print(add)


[20 21 24 26]
[ 3  8 11 15]


In [38]:
del sum

In [40]:
print(np.divide(first,second))
print(np.multiply(first,second))

[0.5        1.66666667 0.83333333 0.875     ]
[ 2 15 30 56]


In [41]:
second = np.array([1,0,6,8])
print(np.divide(first,second))

[1.                inf 0.83333333 0.875     ]


C:\Users\amrit\AppData\Local\Temp\ipykernel_20152\1002426513.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(first,second))


In [42]:
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)

print(np.divide(first,second))

[1.                inf 0.83333333 0.875     ]


In [45]:
arr = np.arange(1,11)
sqq = arr.__pow__(2)

print(arr)
print(f"\n {sqq}")

[ 1  2  3  4  5  6  7  8  9 10]

 [  1   4   9  16  25  36  49  64  81 100]


In [46]:
a = np.array([10,12,15,21])
b = np.array([15,12,10,21])

result = np.mod(a,b)
print(result)

result = np.less(a,b)
print(result)

result = np.less_equal(a,b)
print(result)

result = np.greater_equal(a,b)
print(result)

[10  0  5  0]
[ True False False False]
[ True  True False  True]
[False  True  True  True]


In [49]:
x = np.array([True,False,True,False])
y = np.array([False,False,True,False])

print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x))
print(np.logical_not(y))

[False False  True False]
[ True False  True False]
[False  True False  True]
[ True  True False  True]


In [57]:
result=([2,8,16,32])
percentalie = np.percentile(result, 50)
print(f"50% percentile: {percentalie}")
print("median value: ", np.median(result))

50% percentile: 12.0
median value:  12.0


In [61]:
np_array = np.empty((3,3,3))
print(np_array)


[[[1.25899871e-311 8.69555537e-322 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 1.16095484e-028]
  [6.52022889e+252 7.98581410e-072 4.07186894e+223]]

 [[2.87244884e+161 3.74168445e+233 6.96407614e+252]
  [5.82471389e+257 8.82142681e+199 1.82518707e-076]
  [6.18509535e+223 2.89401333e+243 3.65052563e-143]]

 [[6.96770842e+252 1.78495618e+161 2.16677346e-027]
  [5.28595560e-085 8.14537100e+241 4.03010241e-144]
  [2.91237123e+257 4.71294503e+257 1.29059165e+295]]]


In [62]:
npy_array = np.full(shape=(4,3,5), fill_value=9)
print(npy_array)

[[[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]]


In [64]:
array1 = np.arange(1,49).reshape(3,2,8)
print(array1)

print("\narray based on blocks")

result1 = array1[0]
result1

[[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]]

 [[17 18 19 20 21 22 23 24]
  [25 26 27 28 29 30 31 32]]

 [[33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48]]]

array based on blocks


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [69]:
print(array1[:,1:,:])
print(f"\n\nSecond Column of each matrix\n\n {array1[:,:,1:2]}")

[[[ 9 10 11 12 13 14 15 16]]

 [[25 26 27 28 29 30 31 32]]

 [[41 42 43 44 45 46 47 48]]]


Second Column of each matrix

 [[[ 2]
  [10]]

 [[18]
  [26]]

 [[34]
  [42]]]


In [72]:
np_arrayA = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

np_arrayA[0:2,2] = 10
print(np_arrayA)

[[ 1  2 10]
 [ 4  5 10]
 [ 7  8  9]]
